shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - koa@2.16.3
  - semver@6.3.1

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp

onlyBuiltDependencies:
  - better-sqlite3
