/**
 * String Template Identity function used to manage tailwindcss classnames outside of standard html tags.
 * @param strings
 * @param values
 * @returns string generated by template
 */
export function tw(strings: any, ...values: any[]) {
  return String.raw({ raw: strings }, ...values);
}
